export default {
  ACCESS_TOKEN_PRIVATE_KEY: "ACCESS_TOKEN_PRIVATE_KEY",
  ACCESS_TOKEN_PUBLIC_KEY: "ACCESS_TOKEN_PUBLIC_KEY",
  REFRESH_TOKEN_PRIVATE_KEY: "REFRESH_TOKEN_PRIVATE_KEY",
  REFRESH_TOKEN_PUBLIC_KEY: "REFRESH_TOKEN_PUBLIC_KEY",
};
